# Generated by Django 2.2.6 on 2019-10-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20191019_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Collaborators',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
