# Generated by Django 2.2.6 on 2019-10-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_auto_20191020_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='vote_average',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
