# Generated by Django 2.2.6 on 2019-10-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0005_rating_vote_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='vote_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2),
        ),
    ]
