# Generated by Django 2.2.6 on 2019-10-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_auto_20191021_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='vote_average',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
